version: '3.8'

services:
  ghost:
    image: ghost:latest
    container_name: ghost_app
    restart: always
    depends_on:
      - db
    network_mode: host
    environment:
      url: "https://34.89.34.201"
      database_client: "mysql"
      database_connection_host: "db"
      database_connection_user: "ghost_user"  # Use ghost_user only
      database_connection_password: "newpassword"  # Password for ghost_user
      database_connection_database: "ghost"
    volumes:
      - ghost_content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrongPassword"  # Root password is still required for MySQL container to function
      MYSQL_DATABASE: "ghost"
      MYSQL_USER: "ghost_user"  # Create ghost_user for app-specific DB access
      MYSQL_PASSWORD: "newpassword"  # Password for ghost_user
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 3

volumes:
  ghost_content:
    external: true
    name: ghost-docker_ghost_content
  db_data:
    external: true
    name: ghost-docker_db_data

networks:
  ghost_network:
    driver: bridge
