version: '3'

services:
  ghost_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost_user
      MYSQL_PASSWORD: newpassword
    volumes:
      - ghost-docker_db_data:/var/lib/mysql
    networks:
      - ghost-network

  ghost:
    image: ghost:latest
    environment:
      url: http://localhost:2368
      database_client: mysql
      database_connection_host: ghost_db
      database_connection_user: ghost_user
      database_connection_password: newpassword
      database_connection_database: ghost
    ports:
      - "2368:2368"
    depends_on:
      - ghost_db
    networks:
      - ghost-network

networks:
  ghost-network:

volumes:
  ghost-docker_db_data:
