version: '3.8'

services:
  ghost:
    image: ghost:latest
    container_name: ghost_app
    depends_on:
      - db
    environment:
      url: "https://34.89.34.201"
      database_client: "mysql"
      database_connection_host: "db"
      database_connection_user: "ghost_user"
      database_connection_password: "newpassword"
      database_connection_database: "ghost"
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      - ghost_network

  db:
    image: mysql:8.0
    container_name: ghost_db
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrongPassword"
      MYSQL_DATABASE: "ghost"
      MYSQL_USER: "ghost_user"
      MYSQL_PASSWORD: "newpassword"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ghost_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 3

volumes:
  ghost_content:
    external: true
    name: ghost-docker_ghost_content
  db_data:
    external: true
    name: ghost-docker_db_data

networks:
  ghost_network:
    driver: bridge
