services:
  ghost_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost_user
      MYSQL_PASSWORD: newpassword
    networks:
      - ghost-network

  ghost:
    image: ghost:latest
    environment:
      url: http://localhost:2368
      database_client: mysql
      database_connection_host: ghost_db   # This should be the service name, not 'localhost'
      database_connection_user: ghost_user
      database_connection_password: newpassword
      database_connection_database: ghost
    ports:
      - "2368:2368"
    depends_on:
      - ghost_db
    networks:
      - ghost-network

networks:
  ghost-network:
