version: '3.8'

services:
  ghost:
    image: ghost:latest
    container_name: ghost_app
    depends_on:
      - ghost_db
    network_mode: host  # Use host network mode
    environment:
      url: "https://34.89.34.201"
      database_client: "mysql"
      database_connection_host: "ghost_db"  
      database_connection_user: "ghost_user"
      database_connection_password: "newpassword"
      database_connection_database: "ghost"
      database_root_password: "YourStrongPassword"
     
    volumes:
      - ghost_content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    container_name: ghost_db
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrongPassword"
      MYSQL_DATABASE: "ghost"
      MYSQL_USER: "ghost_user"
      MYSQL_PASSWORD: "newpassword"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  ghost_content:
    external: true
    name: ghost-docker_ghost_content
  db_data:
    external: true
    name: ghost-docker_db_data
